image:
  file: .gitpod.Dockerfile

checkoutLocation: "ignite"

workspaceLocation: "./ignite/.gitpod"

tasks:
  - name: Open the Readme
    command: gp open readme.md

  - name: Setup

    init: |
      ##
      ## install Ignite CLI
      make -C /workspace/ignite install

    command: |
      ##
      # configure env vars.      
      echo "
      export VUE_APP_CUSTOM_URL=$(gp url)
      export CHISEL_ADDR=$(gp url 7575)
      export RPC_ADDRESS=$(gp url 26657):443
      export API_ADDRESS=$(gp url 1317)
      " >> ~/.bashrc && source ~/.bashrc

      echo "
      export VUE_APP_API_COSMOS=${API_ADDRESS}
      export VUE_APP_API_TENDERMINT=${RPC_ADDRESS}
      export VUE_APP_WS_TENDERMINT=${RPC_ADDRESS/https/wss}/websocket
      " >> ~/.bashrc && source ~/.bashrc

      ##
      # cd into the .gitpod dir.
      cd .gitpod

      ##
      # print a welcome message.
      clear && printf '\e[3J'
      echo -e "
      This terminal has the \033[1mignite\033[0m binary already installed and ready to go.
      "

      ##
      # Clone planet project
      git clone https://github.com/anhskrttt/planet-ibc-cosmos.git
      cd planet

      ##
      # final
      gp sync-done ignite

  - name: Start earth
    init: gp sync-await ignite
    command: |
      ignite chain serve -c earth.yml
      # gp sync-done earth

  - name: Start mars
    init: gp sync-await ignite
    command: ignite chain serve -c mars.yml
    openMode: |
      split-right gp sync-done mar

  - name: Config relayer
    init: |
      gp await-port 26657
      gp await-port 26659
    command: |
      ##
      # Remove previous config
      rm -rf ~/.ignite/relayer

      ##
      # Setup relayer
      ignite relayer configure -a \
        --source-rpc "http://0.0.0.0:26657" \
        --source-faucet "http://0.0.0.0:4500" \
        --source-port "blog" \
        --source-version "blog-1" \
        --source-gasprice "0.0000025stake" \
        --source-prefix "cosmos" \
        --source-gaslimit 300000 \
        --target-rpc "http://0.0.0.0:26659" \
        --target-faucet "http://0.0.0.0:4501" \
        --target-port "blog" \
        --target-version "blog-1" \
        --target-gasprice "0.0000025stake" \
        --target-prefix "cosmos" \
        --target-gaslimit 300000

      ## ignite relayer connect
      # Start relayer
      gp sync-done relayer_start

  - name: Send packet from E to M
    init: gp sync-await relayer_start
    command: planetd tx blog send-ibc-post blog channel-0 "Hello" "Hello Mars, I'm Alice from Earth" --from alice --chain-id earth --home ~/.earth

  - name: Send packet from M to E
    init: gp sync-await relayer_start
    command: planetd tx blog send-ibc-post blog channel-0 "Hello" "Hello Earth, I'm Alice from Mars" --from alice --chain-id mars --home ~/.mars --node tcp://localhost:26659

ports:
  - port: 1317
  - port: 26657
  - port: 8080
  - port: 7575
    visibility: public
  - port: 4500
